name: pdf_image_renderer
description: A package that allows fast and simple rendering of pdfs using the native renderers of the OS.
version: 0.8.0
homepage: https://github.com/brettpappas/pdf_image_renderer
repository: https://github.com/brettpappas/pdf_image_renderer
issue_tracker: https://github.com/brettpappas/pdf_image_renderer/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: net.bpi.pdf_image_renderer
        pluginClass: PdfImageRendererPlugin
      ios:
        pluginClass: PdfImageRendererPlugin
